# Generated by Django 4.1.7 on 2023-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(height_field=350, upload_to='media', width_field=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
